package up9_autogenerated_tests

import (
    . "authentication"
    . "up9lib"
    testing "testing"
    uuid "github.com/google/uuid"
)

func TestPutShippingTask016(t *testing.T) {
    for _, tt := range LoadDataset(t, "data/16/dataset_16.json") {
        name := tt.(map[string]interface{})["name"]

        // PUT kafka://kafka/shipping-task (endp 16)
        kafka := GetHttpClient(t, "kafka://kafka", new(Authentication))
        req := new(HttpRequest)
        req.SetHeaders(map[string]interface{}{
            "content-type": "application/json",
        })
        req.SetJsonBody("data/16/payload_for_endp_16.json", map[string]interface{}{
            "$.id": uuid.New().String(),
            "$.name": name,
        })
        kafka.Put(req, "/shipping-task")
    }
}

func TestPutShippingTask149(t *testing.T) {
    // PUT kafka://kafka/shipping-task (endp 149)
    kafka := GetHttpClient(t, "kafka://kafka", new(Authentication))
    req := new(HttpRequest)
    req.SetRawBody(t, "data/149/payload_for_endp_149.txt")
    kafka.Put(req, "/shipping-task")
}
